### ISSUE TITLE
parsing error while using Checkov on tf.json

### ISSUE THREAD

**Issue by hkubram** [bridgecrewio/checkov#1998]
**Describe the bug**

**To Reproduce**
1. Go to the project's directory in the terminal
2. Run cli commands
    terraform init
    terraform plan -out tf.plan
    terraform show -json tf.plan  > tf.json 
    checkov -f tf.json`
3. See error
    Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1
    Error parsing file tf.json terraform_plan scan results:

**Expected behavior**
  There should be no Parsing errors

**Screenshots**
![image](https://user-images.githubusercontent.com/41157379/142707878-cd001dc9-2ff6-43db-a5d0-27916941a033.png)

**Desktop:**
 - OS: Mac
 - Checkov Version 2.0.591

**Comment by Saarett** [comment]
Hi @hkubram , could you please share the file tf.json ?

**Comment by hkubram** [comment]
Sure you can find the JSON file in the link below
https://terraform-plan-file-1.s3.amazonaws.com/tf.json

**Comment by hkubram** [comment]
This issue has been resolved.  Thank you for taking a look.

**Comment by jsimoni** [comment]
I am still getting an error parsing the Terraform plan as json in checkov v2.0.639.
