### ISSUE TITLE
some check are not working as expected when use terraform aws modules

### ISSUE THREAD

**Issue by pgiovio-pomelo** [bridgecrewio/checkov#3354]
**Describe the issue**

I'm having problems with some checks such as CKV_AWS_79 or CKV_AWS_8 when I scan a EC2 instance resource using a AWS external module.

**Examples**
```
module "ec2_instance" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "~> 4.0"

  name = "single-instance"

  ami                    = "ami-ebd02392"
  instance_type          = "t2.micro"
  key_name               = "user1"
  monitoring             = true
  vpc_security_group_ids = ["sg-12345678"]
  subnet_id              = "subnet-eddcdzz4"

  metadata_options = {

       http_endpoint = "enabled"
       http_tokens   = "required"
  }
  
  tags = {
    Terraform   = "true"
    Environment = "dev"
  }
}
```

The expected result is PASS for the check CKV_AWS_79, but I'm getting a FAIL.  Looks like if checkov is not able to resolve the lookup function that the module use in the dynamic "metadata_options" block.  
The same behavior I'm experimenting with other checks like CKV_AWS_8.

**Version (please complete the following information):**
 - Checkov Version 2.0.1211

**Additional context**
I'm executing checkov -d folder/ --config-file conf.yaml

conf.yaml:
```
framework: terraform
hard-fail-on:
- CKV_AWS_3 #Ensure all data stored in the EBS is securely encrypted
- CKV_AWS_37 #Ensure Amazon EKS control plane logging enabled for all log types
- CKV2_AWS_6 #Ensure that S3 bucket has a Public Access block
- CKV_AWS_79 #Ensure Instance Metadata Service Version 1 is not enabled
- CKV_AWS_32 #Ensure ECR policy is not set to public
output:
- github_failed_only
quiet: true
soft-fail: true
```

**Comment by gruebel** [comment]
hey @pgiovio-pomelo thanks for reaching out. This is correct, currently `checkov` doesn't support `dynamic` blocks.

**Comment by ChanochShayner** [comment]
Hey @pgiovio-pomelo
we are now working on supporting dynamic blocks rendering, and we have already implemented a lot in this area.
Could you please try again to scan this resource?

**Comment by IrvicRodriguez** [comment]
> Hey @pgiovio-pomelo
> we are now working on supporting dynamic blocks rendering, and we have already implemented a lot in this area.
> Could you please try again to scan this resource?

Not the original poster but I just created my own EC2 using the module and even after I made the changes I still get soft fail for CKV_AWS_126, CKV_AWS_8 and CKV_AWS_79.

its definitely not detecting changes in modules.

**Comment by abdulakhan-philips-partner** [comment]
Hi there, I am not the OP but I am also not getting any errors from CKV_AWS_54 ([Ensure S3 Bucket BlockPublicPolicy is set to True](https://docs.bridgecrew.io/docs/bc_aws_s3_20) after removing it from my S3 module configuration
